### ISSUE TITLE
Cannot build Ludo due to sha mismatch

### ISSUE THREAD

**Issue by anthonyajumelles** [pdureau/flatpak-manifests#1]
Getting error:

> Failed to download sources: module cores: Wrong sha256 checksum for bluemsx_libretro.so.zip, expected "200ac91011aa01d0d90c9af95534069bd1a07a209e7e7534832a970ff63d1075", was "3f95d4f46935da6ebe4f377fa5a03c6fe16fab508acdef57ba527ef0b853939a"
make: *** [Makefile:10: ludo] Error 1

I imagine the entire set of cores will need sha256s re-applied. 

Might be worth considering bundling a set of default cores so Ludo can be placed on Flathub. This is how Gnome Games does it.

**Comment by pdureau** [comment]
> I imagine the entire set of cores will need sha256s re-applied.

yes, that's the case

> Might be worth considering bundling a set of default cores so Ludo can be placed on Flathub. This is how Gnome Games does it.

Thanks i will have a look

**Comment by pdureau** [comment]
Hello @anthonyajumelles 

I have tried a solution inspired by https://github.com/flathub/org.gnome.Games/tree/master/libretro-cores as you have proposed and it seems to work well.

So, in 5445388e94e0319058dd9a3dbbfd34959a31b2d3 commit , I now have an hybrid situation:
-  18 libretro cores using the former archive source
- 8 libretro cores using the new git source

i will test a bit the new flatpak package and convert everything to the new git source if verything is OK.
